services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: celery -A tasks worker -Q to_compute -l info
    depends_on:
      - redis
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge