services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: celery -A tasks worker -Q to_compute -l info
    depends_on:
      - redis
  